// Code generated by MockGen. DO NOT EDIT.
// Source: command.go
//
// Generated by this command:
//
//	mockgen -source=command.go -destination=mock/command.go -package=mockcommand
//

// Package mockcommand is a generated GoMock package.
package mockcommand

import (
	command "avacado/internal/command"
	protocol "avacado/internal/protocol"
	storage "avacado/internal/storage"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommand is a mock of Command interface.
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
	isgomock struct{}
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCommand) Execute(ctx context.Context, arg1 storage.Storage) *protocol.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, arg1)
	ret0, _ := ret[0].(*protocol.Response)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCommandMockRecorder) Execute(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCommand)(nil).Execute), ctx, arg1)
}

// MockParser is a mock of Parser interface.
type MockParser struct {
	ctrl     *gomock.Controller
	recorder *MockParserMockRecorder
	isgomock struct{}
}

// MockParserMockRecorder is the mock recorder for MockParser.
type MockParserMockRecorder struct {
	mock *MockParser
}

// NewMockParser creates a new mock instance.
func NewMockParser(ctrl *gomock.Controller) *MockParser {
	mock := &MockParser{ctrl: ctrl}
	mock.recorder = &MockParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParser) EXPECT() *MockParserMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockParser) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockParserMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockParser)(nil).Name))
}

// Parse mocks base method.
func (m *MockParser) Parse(msg *protocol.Message) (command.Command, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", msg)
	ret0, _ := ret[0].(command.Command)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockParserMockRecorder) Parse(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockParser)(nil).Parse), msg)
}

// MockParserRegistry is a mock of ParserRegistry interface.
type MockParserRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockParserRegistryMockRecorder
	isgomock struct{}
}

// MockParserRegistryMockRecorder is the mock recorder for MockParserRegistry.
type MockParserRegistryMockRecorder struct {
	mock *MockParserRegistry
}

// NewMockParserRegistry creates a new mock instance.
func NewMockParserRegistry(ctrl *gomock.Controller) *MockParserRegistry {
	mock := &MockParserRegistry{ctrl: ctrl}
	mock.recorder = &MockParserRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParserRegistry) EXPECT() *MockParserRegistryMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockParserRegistry) Parse(msg *protocol.Message) (command.Command, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", msg)
	ret0, _ := ret[0].(command.Command)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockParserRegistryMockRecorder) Parse(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockParserRegistry)(nil).Parse), msg)
}

// Register mocks base method.
func (m *MockParserRegistry) Register(parser command.Parser) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", parser)
}

// Register indicates an expected call of Register.
func (mr *MockParserRegistryMockRecorder) Register(parser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockParserRegistry)(nil).Register), parser)
}

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockValidator) Validate(msg protocol.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockValidatorMockRecorder) Validate(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockValidator)(nil).Validate), msg)
}
