// Code generated by MockGen. DO NOT EDIT.
// Source: hashmaps.go
//
// Generated by this command:
//
//	mockgen -source=hashmaps.go -destination=mock/hashmaps.go -package=mockhashmaps
//

// Package mockhashmaps is a generated GoMock package.
package mockhashmaps

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHashMaps is a mock of HashMaps interface.
type MockHashMaps struct {
	ctrl     *gomock.Controller
	recorder *MockHashMapsMockRecorder
	isgomock struct{}
}

// MockHashMapsMockRecorder is the mock recorder for MockHashMaps.
type MockHashMapsMockRecorder struct {
	mock *MockHashMaps
}

// NewMockHashMaps creates a new mock instance.
func NewMockHashMaps(ctrl *gomock.Controller) *MockHashMaps {
	mock := &MockHashMaps{ctrl: ctrl}
	mock.recorder = &MockHashMapsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashMaps) EXPECT() *MockHashMapsMockRecorder {
	return m.recorder
}

// HGet mocks base method.
func (m *MockHashMaps) HGet(ctx context.Context, name, field string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HGet", ctx, name, field)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HGet indicates an expected call of HGet.
func (mr *MockHashMapsMockRecorder) HGet(ctx, name, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HGet", reflect.TypeOf((*MockHashMaps)(nil).HGet), ctx, name, field)
}

// HSet mocks base method.
func (m *MockHashMaps) HSet(ctx context.Context, name string, keyValues []string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HSet", ctx, name, keyValues)
	ret0, _ := ret[0].(int)
	return ret0
}

// HSet indicates an expected call of HSet.
func (mr *MockHashMapsMockRecorder) HSet(ctx, name, keyValues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HSet", reflect.TypeOf((*MockHashMaps)(nil).HSet), ctx, name, keyValues)
}
