// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mock/storage.go -package=mocksstorage
//

// Package mocksstorage is a generated GoMock package.
package mocksstorage

import (
	kv "avacado/internal/storage/kv"
	lists "avacado/internal/storage/lists"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// KV mocks base method.
func (m *MockStorage) KV() kv.Store {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KV")
	ret0, _ := ret[0].(kv.Store)
	return ret0
}

// KV indicates an expected call of KV.
func (mr *MockStorageMockRecorder) KV() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KV", reflect.TypeOf((*MockStorage)(nil).KV))
}

// Lists mocks base method.
func (m *MockStorage) Lists() lists.Lists {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lists")
	ret0, _ := ret[0].(lists.Lists)
	return ret0
}

// Lists indicates an expected call of Lists.
func (mr *MockStorageMockRecorder) Lists() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lists", reflect.TypeOf((*MockStorage)(nil).Lists))
}
