// Code generated by MockGen. DO NOT EDIT.
// Source: lists.go
//
// Generated by this command:
//
//	mockgen -source=lists.go -destination=mock/lists.go -package=mocklists
//

// Package mocklists is a generated GoMock package.
package mocklists

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLists is a mock of Lists interface.
type MockLists struct {
	ctrl     *gomock.Controller
	recorder *MockListsMockRecorder
	isgomock struct{}
}

// MockListsMockRecorder is the mock recorder for MockLists.
type MockListsMockRecorder struct {
	mock *MockLists
}

// NewMockLists creates a new mock instance.
func NewMockLists(ctrl *gomock.Controller) *MockLists {
	mock := &MockLists{ctrl: ctrl}
	mock.recorder = &MockListsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLists) EXPECT() *MockListsMockRecorder {
	return m.recorder
}

// LPush mocks base method.
func (m *MockLists) LPush(key string, values ...[]byte) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LPush", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LPush indicates an expected call of LPush.
func (mr *MockListsMockRecorder) LPush(key any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LPush", reflect.TypeOf((*MockLists)(nil).LPush), varargs...)
}
