// Code generated by MockGen. DO NOT EDIT.
// Source: lists.go
//
// Generated by this command:
//
//	mockgen -source=lists.go -destination=mock/lists.go -package=mocklists
//

// Package mocklists is a generated GoMock package.
package mocklists

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLists is a mock of Lists interface.
type MockLists struct {
	ctrl     *gomock.Controller
	recorder *MockListsMockRecorder
	isgomock struct{}
}

// MockListsMockRecorder is the mock recorder for MockLists.
type MockListsMockRecorder struct {
	mock *MockLists
}

// NewMockLists creates a new mock instance.
func NewMockLists(ctrl *gomock.Controller) *MockLists {
	mock := &MockLists{ctrl: ctrl}
	mock.recorder = &MockListsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLists) EXPECT() *MockListsMockRecorder {
	return m.recorder
}

// LIndex mocks base method.
func (m *MockLists) LIndex(ctx context.Context, key string, index int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LIndex", ctx, key, index)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LIndex indicates an expected call of LIndex.
func (mr *MockListsMockRecorder) LIndex(ctx, key, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LIndex", reflect.TypeOf((*MockLists)(nil).LIndex), ctx, key, index)
}

// LPop mocks base method.
func (m *MockLists) LPop(ctx context.Context, key string, count int) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LPop", ctx, key, count)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LPop indicates an expected call of LPop.
func (mr *MockListsMockRecorder) LPop(ctx, key, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LPop", reflect.TypeOf((*MockLists)(nil).LPop), ctx, key, count)
}

// LPush mocks base method.
func (m *MockLists) LPush(ctx context.Context, key string, values ...[]byte) (int, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LPush", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LPush indicates an expected call of LPush.
func (mr *MockListsMockRecorder) LPush(ctx, key any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LPush", reflect.TypeOf((*MockLists)(nil).LPush), varargs...)
}

// Len mocks base method.
func (m *MockLists) Len(ctx context.Context, key string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len", ctx, key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Len indicates an expected call of Len.
func (mr *MockListsMockRecorder) Len(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockLists)(nil).Len), ctx, key)
}

// RPop mocks base method.
func (m *MockLists) RPop(ctx context.Context, key string, count int) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RPop", ctx, key, count)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RPop indicates an expected call of RPop.
func (mr *MockListsMockRecorder) RPop(ctx, key, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RPop", reflect.TypeOf((*MockLists)(nil).RPop), ctx, key, count)
}

// RPush mocks base method.
func (m *MockLists) RPush(ctx context.Context, key string, values ...[]byte) (int, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RPush", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RPush indicates an expected call of RPush.
func (mr *MockListsMockRecorder) RPush(ctx, key any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RPush", reflect.TypeOf((*MockLists)(nil).RPush), varargs...)
}
