// Code generated by MockGen. DO NOT EDIT.
// Source: hashsets.go
//
// Generated by this command:
//
//	mockgen -source=hashsets.go -destination=mock/hashsets.go -package=mockhashsets
//

// Package mockhashsets is a generated GoMock package.
package mockhashsets

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHashSets is a mock of HashSets interface.
type MockHashSets struct {
	ctrl     *gomock.Controller
	recorder *MockHashSetsMockRecorder
	isgomock struct{}
}

// MockHashSetsMockRecorder is the mock recorder for MockHashSets.
type MockHashSetsMockRecorder struct {
	mock *MockHashSets
}

// NewMockHashSets creates a new mock instance.
func NewMockHashSets(ctrl *gomock.Controller) *MockHashSets {
	mock := &MockHashSets{ctrl: ctrl}
	mock.recorder = &MockHashSetsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashSets) EXPECT() *MockHashSetsMockRecorder {
	return m.recorder
}

// HSet mocks base method.
func (m *MockHashSets) HSet(ctx context.Context, keyValues []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HSet", ctx, keyValues)
}

// HSet indicates an expected call of HSet.
func (mr *MockHashSetsMockRecorder) HSet(ctx, keyValues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HSet", reflect.TypeOf((*MockHashSets)(nil).HSet), ctx, keyValues)
}
