// Code generated by MockGen. DO NOT EDIT.
// Source: protocol.go
//
// Generated by this command:
//
//	mockgen -source=protocol.go -destination=mock/protocol.go -package=mockprotocol
//

// Package mockprotocol is a generated GoMock package.
package mockprotocol

import (
	protocol "avacado/internal/protocol"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockParser is a mock of Parser interface.
type MockParser struct {
	ctrl     *gomock.Controller
	recorder *MockParserMockRecorder
	isgomock struct{}
}

// MockParserMockRecorder is the mock recorder for MockParser.
type MockParserMockRecorder struct {
	mock *MockParser
}

// NewMockParser creates a new mock instance.
func NewMockParser(ctrl *gomock.Controller) *MockParser {
	mock := &MockParser{ctrl: ctrl}
	mock.recorder = &MockParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParser) EXPECT() *MockParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockParser) Parse(r io.Reader) (*protocol.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", r)
	ret0, _ := ret[0].(*protocol.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockParserMockRecorder) Parse(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockParser)(nil).Parse), r)
}

// MockSerializer is a mock of Serializer interface.
type MockSerializer struct {
	ctrl     *gomock.Controller
	recorder *MockSerializerMockRecorder
	isgomock struct{}
}

// MockSerializerMockRecorder is the mock recorder for MockSerializer.
type MockSerializerMockRecorder struct {
	mock *MockSerializer
}

// NewMockSerializer creates a new mock instance.
func NewMockSerializer(ctrl *gomock.Controller) *MockSerializer {
	mock := &MockSerializer{ctrl: ctrl}
	mock.recorder = &MockSerializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSerializer) EXPECT() *MockSerializerMockRecorder {
	return m.recorder
}

// Serialize mocks base method.
func (m *MockSerializer) Serialize(value *protocol.Response) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serialize", value)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Serialize indicates an expected call of Serialize.
func (mr *MockSerializerMockRecorder) Serialize(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serialize", reflect.TypeOf((*MockSerializer)(nil).Serialize), value)
}

// SerializeError mocks base method.
func (m *MockSerializer) SerializeError(e error) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SerializeError", e)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// SerializeError indicates an expected call of SerializeError.
func (mr *MockSerializerMockRecorder) SerializeError(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SerializeError", reflect.TypeOf((*MockSerializer)(nil).SerializeError), e)
}

// MockProtocol is a mock of Protocol interface.
type MockProtocol struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolMockRecorder
	isgomock struct{}
}

// MockProtocolMockRecorder is the mock recorder for MockProtocol.
type MockProtocolMockRecorder struct {
	mock *MockProtocol
}

// NewMockProtocol creates a new mock instance.
func NewMockProtocol(ctrl *gomock.Controller) *MockProtocol {
	mock := &MockProtocol{ctrl: ctrl}
	mock.recorder = &MockProtocolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocol) EXPECT() *MockProtocolMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockProtocol) Parse(r io.Reader) (*protocol.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", r)
	ret0, _ := ret[0].(*protocol.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockProtocolMockRecorder) Parse(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockProtocol)(nil).Parse), r)
}

// Serialize mocks base method.
func (m *MockProtocol) Serialize(value *protocol.Response) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serialize", value)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Serialize indicates an expected call of Serialize.
func (mr *MockProtocolMockRecorder) Serialize(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serialize", reflect.TypeOf((*MockProtocol)(nil).Serialize), value)
}

// SerializeError mocks base method.
func (m *MockProtocol) SerializeError(e error) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SerializeError", e)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// SerializeError indicates an expected call of SerializeError.
func (mr *MockProtocolMockRecorder) SerializeError(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SerializeError", reflect.TypeOf((*MockProtocol)(nil).SerializeError), e)
}
